### ISSUE TITLE
Build 6 Ideas

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#1]
Current changes:

Fighers:
- hw1 int/bomber res 800 -> 500 ru 30 -> 25 secs (should be cheaper than hw2 considering hw1 int/bombers are slightly worse than hw2)

Corvettes:
- hw1 multigun vett res 1000 -> 800 ru 60 -> 50 secs (too much for just a better version of the light vett)
- hw1 salvage vett hp 1000 -> 1500 (build 4) -> 1200 (build 6) (buff was to make up for the salvette bug, but 1000 is still too easy to kill)
- hw1 salvage vett 255 -> 290 (build 4) -> 255 (build 6) (same reason as above)

Frigates:
- hw1 drone frigate 900 -> 800 (build 5) -> 700 ru (build 6) (not really worth the cost)
- hw1 drone frigate res 1300 -> 1000 ru 80 -> 60 secs (not worth it for what is mainly an anti fighter unit)
- hw1 assault frigate turret turn speed +100% (25 -> 50, vaygr assault frigate is 60)
- hw1 assault gun and bomb speed +100% (to hit hw2 vetts more reliably)
- hw1 assault frigate bomb now leads shots on enemies (to hit hw2 vetts more reliably)
  (assault frigates are much worse at killing vetts compared to torpedo frgiates, they are still a bit slower but do kill moving vetts alot faster)
- hw1 assault frigate gun accuracy vs fighters -20% (because the speed increase made them able to beat bombers)

Other ideas:
- since hw1 refineries only get 1 docking port maybe they should have a higher unit cap
- hw1 research should not include the cost of mods, the cost of mods should be paid in terms of a more expensive economy (ei in collectors and refineries) since they are the closest hw1 gets to mods (they can be lost and limit the amount of production if lost, research is paid once and cant be lost)
- costs for things like support frigates and carriers should be nominal
- hw1 dds and bcs cost more than hw2, would be better if they are as close to identical as possible in terms of performance and costt. hw2 battlecruisers beat hw1 heavycruisers despite them costing more (hw1 wins on about 10% hp thinking the fix would be to reduce to 4000 ru and to buff hp to same as hw2 lvl 1 res)
- hw1 capital res is still too much

**Comment by RoBeY4Gate** [comment]
Approve, ready to test whenever we are online. Hopefully fear has a good look though.
