### ISSUE TITLE
HW2 Collector Repair Research Cost

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#11]
Already costs rus to repair in lost mining time. Something like 200ru and reduced time would make it more viable.

**Comment by S5SS** [comment]
changed title

**Comment by S5SS** [comment]
Currently 200ru and 20 secs for both hiig and vaygr in the ssss branch.

**Comment by Novaras** [comment]
perhaps this ability should just be innate

you said earlier today you wanted to avoid shuffling around tech, but i dont see much harm in just making the rep ability innate

**Comment by S5SS** [comment]
I really do want the tech tree to stay the same. I think that was one of the best things about 2.3, you don't need to learn anything new to know how things work even if its pretty harmless. I think it would have been innate in the first place but I think settling for almost innate is good enough.

Perhaps research time could be further reduced, perhaps like 15 seconds or something.

**Comment by Novaras** [comment]
is the repair rate fast enough though? contrast to repair vettes i'd say

**Comment by S5SS** [comment]
I made it a bit faster especially for frigates iirc but perhaps it could be higher, needs testing

**Comment by S5SS** [comment]
20 seconds feel fine though to me, compared to other research its one of the fastest in the game for hw2 if not fastest

**Comment by Novaras** [comment]
yeah im down for these changes then, dont want to overbuff or such
