### ISSUE TITLE
Non-Bomber Subsystem Damage

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#12]
Getting modules killed by ints doesn't make much sense imo

**Comment by Novaras** [comment]
at the same time, i dont think ints should be *incapable* of killing subs

any specific cases which are aggravating?

**Comment by S5SS** [comment]
Its just feels unbalanced when a swarm of ints can kill a hiig res mod or kill an inhib/cloak facility. Bombers are slow so that you have a chance to kill them before they take out mods but thats not the case vs ints. Max ints take too long to kill compared to bombers imo aswell.

**Comment by Novaras** [comment]
part of larger issue with insanely long TTK against strikecraft in this game, as well as huge variance in TTK

i'd say max ints should be able to kill a module though - if we're talking about <=8 squads probably not

**Comment by S5SS** [comment]
They should be able to but it has to take a fair bit longer than it does now imo, Id be happy with say -50% dmg to subsystems for ints

**Comment by Novaras** [comment]
my main issue is that ive never really noticed anyone else had a problem

i dont mind a small nerf, but 50% just destroys them here completely

**Comment by S5SS** [comment]
Hmm would something more like -30% be ok then?

**Comment by Novaras** [comment]
yeah, 20% would be my goto, 30% is fine in my opinion though

**Comment by Novaras** [comment]
Thinking about it, I remember int damage Vs subs was buffer at some point? Probably need to poke cloaked in case that was his idea for justification

**Comment by S5SS** [comment]
Yeah it was, in vgr_flechettecannon and hgn_kineticautogun the penetration went from 1.0 in 2.1 to 1.4 in 2.3 so -30% would bring it down to 0.98. I think it should just be set back to 1.0 really. To me ints arent units that should be able to kill modules (atleast quickly), bombers are in the same unit class yet are barely even needed for mods if you have max ints - you can end so many fun strats by just killing a mod with ints that I think it reduces the number of viable strats instead of increasing it

**Comment by Novaras** [comment]
I'm fine with it being 1.0 again then
