### ISSUE TITLE
More Missing VO Lines

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#13]
Missile platform: Heavy missile ~~frigate complete~~ + platform complete

**Comment by Novaras** [comment]
is this just vgr? what is missing

**Comment by S5SS** [comment]
I don't know of any other missing ones, I just put this here incase anyone else can remember more missing lines. The missile platform vo doesn't sounds right at all though, he says missile frigate as one word so it sounds unnatural when it gets chopped in half so that one can be scrapped.

**Comment by Novaras** [comment]
so just use 'platform complete' right? is this on ssss?

**Comment by S5SS** [comment]
Yeah its platform complete in build 8 already for both platforms, I was just seeing if I could make it more specific for each platform type but I don't think its possible

**Comment by Novaras** [comment]
shall i close this then?
