### ISSUE TITLE
Hgn DD out-of-combat regen

### ISSUE THREAD

**Issue by Novaras** [S5SS/dual-command#14]
Feature branch here: https://github.com/S5SS/dual-command/tree/hgn_dd_regen

- should this even be a thing
- how long OOC should a dd be before regeneration kicks in?
- should dd's have innate regeneration? should it all come from this ability?
- how strong should it be?

**Comment by S5SS** [comment]
I think its an cool mechanic ,what exactly is it supposed to do to destroyers though? Do you just want them to be hit and run type units?

**Comment by Novaras** [comment]
their whole idea is kiting, so you should probably be more obviously rewarded for doing that

**Comment by Novaras** [comment]
for reference:
https://www.youtube.com/watch?v=DcKcmtnGKpw

**Comment by S5SS** [comment]
What kind of buffs are you thinking of making to other destroyers to make up for the buff to hiig dds?

**Comment by Novaras** [comment]
vgr DD should probably have a DPS buff? feels like a bit of an uninspired buff and keeps it as a big HMF though...

**Comment by S5SS** [comment]
We want to try making hw2 collector repair more viable to implement this as a vanilla solution so this can be closed for now.
