### ISSUE TITLE
HW1 research exposure

### ISSUE THREAD

**Issue by Novaras** [S5SS/dual-command#17]
I'm thinking its pretty possible to cause a corresponding module to spawn on the research ship after the tech is obtained.

Regardless of how its achieved, is this worth doing at all?

**Comment by S5SS** [comment]
I think this is how it should have been to begin with but I think it would be too big of a change compared to vanilla. Perhaps hangar sizes could be reduced so someone cant hide int/vett choice as well early game but this has other disadvantages too

**Comment by Novaras** [comment]
After talking with S for a bit about this, hw1 having totally hidden tech is becoming a more apparent issue as games get closer and more glaring issues are being worked out.

As a remedy, it should be fairly straightforward to add lights to the ship to indicate certain tech.

Something that may be worth thinking about - hw1 is possibly at a disadvantage with this as hw2 races only show their tech on construction modules which they can potentially sell to hide the fact that they built a sneak frigate or something. Hw1 will display their frigate tech permanently.

**Comment by Novaras** [comment]
maybe production ships should instead show this, but when building?

**Comment by S5SS** [comment]
Im fine with it on production ships, its the same disadvantage hw2 gets after all except they cant sell the mods to hide tech, but then again they get an advantage in that bombers cant kill them.

**Comment by S5SS** [comment]
Implemented in build 10
