### ISSUE TITLE
interceptors too weak vs colls

### ISSUE THREAD

**Issue by Novaras** [S5SS/dual-command#18]
currently interceptors are hardly worth attacking with unless you can gather up perhaps 8+ squads

even then, they only really perform decently against unupgraded hw2 colls, upgraded hw2 and hw1 colls are incredibly tough

with the counter-fighter units being generally buffed over time, ints can probably have some power returned to them - although buffs should be cautious as ints were beyond S+ tier back in 2.1

**Comment by S5SS** [comment]
Yep, I agree

**Comment by Novaras** [comment]
This was shipped with build 9
