### ISSUE TITLE
Friendly Fire Damage

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#28]
Used to be 0.5 in 2.3 and 2.1 but I changed it to 1.0 in dual for consistency but it may be better overall to just keep it at 0.5.

**Comment by Novaras** [comment]
afaik EMP shields were based around the 0.5 multiplier, probably best to revert as I don't see any real benefit of 1.0?

**Comment by S5SS** [comment]
Ok Im fine with 0.5 again. I just like consistency which is why I set it to 1.0

**Comment by Novaras** [comment]
https://github.com/S5SS/dual-command/pull/30
