### ISSUE TITLE
Making Build and Research Times the Default Option

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#29]
Think it should be on by default? I have a feeling its one of those features 90% of people won't know about unless its on by default.

**Comment by Novaras** [comment]
why is it not default? languages or something?

**Comment by S5SS** [comment]
Yeah thats why, the people we play with know English anyway so maybe its not that big of a deal. I think people would understand better the balance we are going for if they could see the build times.

**Comment by S5SS** [comment]
Changed to default
