### ISSUE TITLE
cloaked fighter regen

### ISSUE THREAD

**Issue by Novaras** [S5SS/dual-command#31]
kus is not worth playing at all, want to highlight their unique units some more as they still aren't used at all

feel like giving them regen out of combat, and maybe also a tiny hp buff as well as reducing their tech cost:

---
## Cloaked Fighters
>*Still a never-seen unit (for the wrong reasons). Kushan struggles to justify its existence in multiplayer games and has no real advantage over taii field technology.*
* **Out-of-combat regen added:** `0.75 HP/s` // Regenerates from 0 to max in 3 minutes. Being 'out-of-combat' takes 5 seconds of no damage taken.
  *  **Glow effect added to regenerating fighters**
* **Research cost down:** `1000 => 825`
* **Research time down:** `80 => 75`
* **Build cost down:** `120 => 110`
* **Build time down:** `12 => 10`
---

**Comment by S5SS** [comment]
Sounds reasonable to me

**Comment by Novaras** [comment]
https://github.com/S5SS/dual-command/pull/32
