### ISSUE TITLE
HW1 Interceptor HP

### ISSUE THREAD

**Issue by S5SS** [S5SS/dual-command#38]
When I was buffing hw1 ints they were both slower to build and had less HP so I buffed both but now they are very spammable so perhaps a reduction to HP would make them more manageable. Buffed from 90 hp to 110 hp so maybe reduce them back to 100 hp for a start.

**Comment by Novaras** [comment]
yes please god, hw1 int spam is pure insanity right now

they could even stand to have a second added to their build time

**Comment by S5SS** [comment]
Hmm we could try that if a hp nerf isn't enough, but for now if you have no objections I think we should start with just -10hp so we dont accidentally over nerf them. They take 40 seconds to build 5 ints rn whereas for hw2 its 35 and even less with imp man.

**Comment by S5SS** [comment]
#45

**Comment by Novaras** [comment]
https://github.com/S5SS/dual-command/issues/51
