### ISSUE TITLE
Kus and Tai gravwells have different energy pools

### ISSUE THREAD

**Issue by Novaras** [S5SS/dual-command#53]
Tai has `166`, Kus has `200`

At a burn rate of `6.5` energy/s, we get a tai who can only maintain `25s` and kus who can maintain `30s`. Not sure how this got in.

~~Will be naturally fixed in tandem with https://github.com/S5SS/dual-command/issues/52 so both last for `30s`~~

**Comment by Novaras** [comment]
This fix is actually bundled in https://github.com/S5SS/dual-command/pull/54 instead

**Comment by S5SS** [comment]
Hmm what if they were both 25s, 30s is quite long just for one grav.

**Comment by Novaras** [comment]
If I can't make activation cost work, we'll do 25s
