### ISSUE TITLE
Truly disabling hyperspace inside inhibs

### ISSUE THREAD

**Issue by Novaras** [S5SS/dual-command#55]
So I just discovered this is actually very trivial:

For subs:
`AddSubSystemAbility(NewShipType, "Hyperspace", 0, "EnemyShipsWithinRadius", 10500)`

For ships (like gws):
`AddShipAbility(NewShipType, "Hyperspace", 0, "EnemyShipsWithinRadius", 10500)`

**I haven't tested whether the subsystem effect works, just the ships. This is because I'm really lazy**

https://github.com/S5SS/dual-command/pull/54

**Comment by S5SS** [comment]
Fixed
